version: "3.8"
services:
  # 1 kontener z bazą
  mongodb:
    image: 'mongo'
    ports:
      - "27017:27017"
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
  # 2 kontenter z aplikacją
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

