version: "3.8"
services:

#Kontener mongodb
  mongodb:
    image: mongo:6.0
    container_name: springboot-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - springboot-network

  #Kontener spring-boot
  springboot-app:
    build:
      context: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/test
    depends_on:
      - mongodb
    networks:
      - springboot-network

volumes:
  mongo_data:
networks:
  springboot-networks:
