version: "3.8"
services:

#Kontener mongodb
  mongodb:
    image: 'mongo'
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

#Kontener spring-boot
  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/test
    depends_on:
      - mongodb

volumes:
  mongo_data:

